### ISSUE TITLE
Make Tripal Content Permissions Dynamic (i.e. per Type)

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1355]
## Task Description

We want to allow assigning of permissions on a per-content type basis for Tripal Content similar to that done in Drupal core for nodes. 

<img width="1462" height="871" alt="Image" src="https://github.com/user-attachments/assets/61d51c5c-dba9-467f-8e56-76548a575dad" />

Specifically, we want the following options for each Tripal Content type:
- _Content Type:_ Create new content
- _Content Type:_ Edit any content
- _Content Type:_ Edit own content
- _Content Type:_ Delete any content
- _Content Type:_ Delete own content
- _Content Type:_ View all content
- _Content Type:_ View own content

## Current state of things

Currently we have general permissions for CRUD operations on Tripal Content in `tripal/tripal.permissions.yml` as shown below:

```yml
add tripal content entities:
  title: 'Create new Tripal Content'

edit tripal content entities:
  title: 'Edit Tripal Content'

delete tripal content entities:
  title: 'Delete Tripal Content'

view published tripal content entities:
  title: 'View published Tripal Content'

view unpublished tripal content entities:
  title: 'View unpublished Tripal Content'
```

These need to be removed and permissions should be generated via a custom permissions class. Then access is determined by a custom access class.

We actually have a couple of custom access classes already left over from an attempt at providing this functionality earlier. Those can be found here:

- [Drupal\tripal\Access\TripalEntityAccessControlHandler](https://github.com/tripal/t4d8/blob/9.x-4.x/tripal/src/Access/TripalEntityAccessControlHandler.php).
- [Drupal/tripal/src/Access/TripalEntityAccessOwnContentCheck](https://github.com/tripal/tripal/blob/4.x/tripal/src/Access/TripalAccessOwnContentCheck.php)

But we don't appear to have a matching permission class.

## Design

We will want to 

1. Remove the existing hard-coded permissions for entities in the `tripal/tripal.permissions.yml` file.
2. Create `Drupal\tripal\Access\TripalEntityPermissions` class using [NodePermissions](https://api.drupal.org/api/drupal/core%21modules%21node%21src%21NodePermissions.php/class/NodePermissions/11.x) as an example.
3. Update [Drupal\tripal\Access\TripalEntityAccessControlHandler](https://github.com/tripal/t4d8/blob/9.x-4.x/tripal/src/Access/TripalEntityAccessControlHandler.php) to grant access to specific users based on the permissions defined above using [NodeAccessControlHandler](https://api.drupal.org/api/drupal/core%21modules%21node%21src%21NodeAccessControlHandler.php/class/NodeAccessControlHandler/11.x) as an example.

## Branch Name

`tv4g1-issue1355-perContentTypePermissions`
