### ISSUE TITLE
Chado cvterm autocomplete

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1482]
# Core Tripal 4 Development Task

## Branch Name: tv4g2-issue1482-chadoCvtermAutocomplete

We need an autocomplete in tripal_chado to help people select Chado cvterms. We have an autocomplete for Tripal Terms (which is confusingly named IMO) but this is not sufficient as it will only show a subset of the terms in the chado cvterm table (those initialized as Tripal terms). There are many cases such as in our importers and configuration forms where curators/admin should have access to all cvterms in chado.

### Plan

1. Add a route to the tripal_chado.routing.yml for the autocomplete. Something like
```yml
tripal_chado.cvterm_autocomplete:
  path: 'chado/cvterm/autocomplete/{count}'
  defaults:
    _controller: '\Drupal\tripal_chado\Controller\ChadoCVTermAutocompleteController::handleAutocomplete'
    _title: 'Chado Vocabulary Term Autocomplete'
    _format: json
  requirements:
    _permission: 'access content'
```

2. Create a controller for the autocomplete at `tripal_chado/src/Controllers` with the following methods: 

 - `handleAutocomplete()`: queries chado and provides options in the format "*cvterm.name* (*db.name*:*dbxref.accession*)" to match the format of the autocomplete for Tripal terms.
 - `getCVtermID()`: retrieves the cvterm_id based on the information in a user submitted autocomplete option. Specifically which takes a "*cvterm.name* (*db.name*:*dbxref.accession*)" string as input and returns the cvterm_id. This should a public static method so that it can be called in the form submit without creating an object.

3. Handle the cv as an optional parameter to the autocomplete which restricts the terms provided to the user to that cv.
