### ISSUE TITLE
Cvterm autocomplete needs filter by cv 

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1571]
# Core Tripal 4 Development Task

## Pull #1585

The [Cvterm Autocomplete](https://github.com/tripal/tripal/blob/4.x/tripal_chado/src/Controller/ChadoCVTermAutocompleteController.php) needs to be able to filter by cv. This was [mentioned as a todo in the code](https://github.com/tripal/tripal/blob/4.x/tripal_chado/src/Controller/ChadoCVTermAutocompleteController.php#L17-L18) as it is needed for multiple importers. An example of this is the FASTA importer for which the drop-down will only select sequence ontology terms. In it's current implementation, the cvterm autocomplete used on the fasta importer allows you to pick any term and then the validation fails if it is not a sequence ontology term. Ideally you would only be able to select valid terms 😜 

## Approach

We need to change the autocomplete parameters in routing to include the cv_id. This should be added after count and it should be optional since some cvterm autocompletes do want access to all terms.

https://github.com/tripal/tripal/blob/4.x/tripal_chado/tripal_chado.routing.yml#L141-L148
```yaml
tripal_chado.cvterm_autocomplete:
  path: 'chado/cvterm/autocomplete/{count}'
  defaults:
    _controller: '\Drupal\tripal_chado\Controller\ChadoCVTermAutocompleteController::handleAutocomplete'
    _title: 'Chado Vocabulary Term Autocomplete'
    _format: json
  requirements:
    _permission: 'access content'
```

Next you will change the handleAutocomplete() method to handle an optional cv_id.

https://github.com/tripal/tripal/blob/4.x/tripal_chado/src/Controller/ChadoCVTermAutocompleteController.php#L13-L73

The remaining methods in the autocomplete controller should be good as is since they depend on an already chosen term and do not need to be restricted thus.

Once you finish the above, you will want to add additional asserts to the cvterm test to make sure this functionality works in the automated setting and that it continues to work ;-)

You'll also want to update the FASTA importer to restrict to the sequence ontology. This then provides a way to manually test in the form. You can also manually test using the route itself.
