### ISSUE TITLE
Support Joins for Finding Values

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1719]
### Task Description

Our current approach in fields for modeling the joins needed for inserting, updating and selecting all field values when the primary key of a base table record is known works well. However, this approach is insufficient for finding records when values in non-base tables are needed to find records in base tables. 

## Join Use Cases
Currently we support joins in fields using two different methods:
1.	CASE 1: The `store_link` action.   A join is specified using the `left_table`, `left_table_id`, `right_table` and `right_table_id` property storage settings.   The `ChadoStorage` plugin uses these values to create a “path” that is passed to the `ChadoStorage::addChadoRecordJoins()` function.
2.	CASE 2: The `read_value` action.  A join is specified using the `path` property storage settings. This path is passed directly to the `ChadoStorage::addChaodRecordJoins()` function.

## Review of how joins are currently handled.
Both CASE 1 and CASE 2 end up using the `ChadoStorage::addChadoRecordJoins()` to add joins. The code from that function that adds the join to the records object is as follows:

https://github.com/tripal/tripal/blob/6779fccbf67d58950b6186eb9c82f990d48d33bd/tripal_chado/src/Plugin/TripalStorage/ChadoStorage.php#L1714-L1727 

Note that aliases for tables in a join are given a numeric suffix based on the order in which a table is added.  If a table is only added once to a join then the suffix is always 0. But the second time, it will have a suffix of 1.  This can happen for tables such as `featureloc` because it has a `feature_id` and `srcfeature_id` column that both join to the `feature` table.  

For insert, update or selecting of a single record these aliases don’t matter because we also give an alias to the column we want via the `as` property in the `read_value` action.  So regardless of the table aliasing we can always pull out a unique column. 

Also, note that the “base” table in the joins is referred to as “ct” (an abbreviation for “chado table”, or “base table”).

## Challenges for finding values.
For finding values, we intend to find all base table records that match a set of criteria.  Theoretically, we should be able to find records using values set for any field property on the content type.  

### Publishing Use Case:
One use case for finding values, is in publishing. For example, the “Genome Assembly” content type requires that the `type_id` for an analysis base record be set in the `analysisprop` table.  So, to publish, we must first find all the analyses with an associated record in the analysisprop table.   If we look at the `ChadoAdditionalTypeTypeDefault` plugin class. We see that the join is specified via a property with a `store_link` action:
https://github.com/tripal/tripal/blob/6779fccbf67d58950b6186eb9c82f990d48d33bd/tripal_chado/src/Plugin/Field/FieldType/ChadoAdditionalTypeTypeDefault.php#L132-L136
The value of the `type_id` comes from a property with a `store` action.
https://github.com/tripal/tripal/blob/6779fccbf67d58950b6186eb9c82f990d48d33bd/tripal_chado/src/Plugin/Field/FieldType/ChadoAdditionalTypeTypeDefault.php#L145-L150 

#### Problem  1
First, the `link_id` field is missing the `left_table`, `left_table_id`, `right_table` and `right_table_id` properties. That’s okay, it just hasn’t been updated yet.  But let’s assume they are there to indicate how the table should join to the base table.  I’ve fixed this in my current working branch `tv4g2-issue1515-publish_chado_content`

#### Problem 2
The record array structure that ChadoStorage used for representing how to query cannot currently handle adding conditions on joined tables.  Here’s what it current looks like (in YAML format) for finding analyses:

```
analysis:
- conditions:
    analysis_id:
      value:
      - REPLACE_BASE_RECORD_ID
      - analysis
      operation: =
  fields:
    analysis_id: ~
    name: ~
  joins:
    analysisprop:
      analysis_id:
        "on":
          left_table: analysis
          left_col: analysis_id
          right_table: analysisprop
          right_col: analysis_id
          left_alias: analysis
          right_alias: analysisprop
        columns:
        - - analysis_id
          - link_id
          - genome_assembly_type
          - link_id
```
In order to filter (or find) base records that have conditions in joined tables we need to specify the table. In my current working branch this is how I changed the array:

```
analysis:
- conditions:
    analysis:
      analysis_id:
        value:
        - REPLACE_BASE_RECORD_ID
        - analysis
        operation: =
    analysisprop:
      type_id:
        value: "31"
        operation: =
  fields:
    analysis_id: ~
    name: ~
  joins:
    analysisprop:
      analysis_id:
        "on":
          left_table: analysis
          left_col: analysis_id
          right_table: analysisprop
          right_col: analysis_id
          left_alias: analysis
          right_alias: analysisprop
        columns:
        - - analysis_id
          - link_id
          - genome_assembly_type
          - link_id
```
Notice how the table name for the condition is now above the criteria.  This fix allows us to find analyses that are only “Genome Assembly” records and publish those!  It’s currently working using this approach.

#### Problem 3
The change to the records array structure to support conditions on non-base tables works because I also had to make a change in the `ChadoStorage::addChadoRecordJoins()` function.  In this use case, the `analysisprop` table is joined to the `analysis` table because the `link_id` property provides that join. The `type_id` property takes advantage of that join.  In the current `addChadoRecordJoins()` function (see code above) the join will create the alias `janalysisprop0` for the anaysisprop table.   Unfortunately, the `type_id` property doesn’t know what the alias is.   It would be unreasonable to expect the field developer to know this alias, and even less to know the order in which tables with the same name are joined. As long is there is only one instance of a table joined all is fine if the developer knows to use the fromat similar to `janalysisporp0` in a `chado_table_alias` property setting.  Since that did not seem reasonable, I changed the `ChadoStorage::addChadoRecordJoins()` to not add the `j` prefix nor the numeric suffix if the table was the first one.   The developer need not provide any additional settings. 

### Future Issues
In the process of adding fixes for the use case above I realized that we would continue to have problems when finding values because:

1.	Field properties rely on other properties to specify a join.  This is ambiguous.   For example, If we wanted to find a feature (via the `featureloc` table) with a given name (gene) located on another feature of a given name (e.g. chromosome) then we have to join twice on the feature table.  There is no way for the field properties to know which join of the feature table they should use to set a conditional value.  The `store_link` property could set an alias, but the feature `name` property doesn’t know which alias to use.  
2.	The `addChadoRecordJoins()` sets the table aliases.  This means it’s not possible for a field to know what the table alias is.  My solution for the publishing use case works as long as the table only occurs once in the joins.

### Possible Solution
Use a specific `path` attribute for all properties.  This would follow the same convention as the `path` setting does for the properties with a `read_value` action. One change is to add the column where the value comes from to the end of the path. Consider this for the `ChadoAdditionlaTypeTypeDefault` field

```php
if ($type_table != $base_table) {
      $type_table_def = $schema->getTableDef($type_table, ['format' => 'Drupal']);
      $type_pkey_col = $type_table_def['primary key'];
      $type_fkey_col = array_keys($type_table_def['foreign keys'][$base_table]['columns'])[0];
      $link_term = $mapping->getColumnTermId($type_table, $type_fkey_col);
      $value_term = $mapping->getColumnTermId($type_table, 'value');

      $properties[] = new ChadoIntStoragePropertyType($entity_type_id, self::$id, 'prop_id', $record_id_term, [
        'action' => 'store_pkey',
        'drupal_store' => TRUE,
        'path' => $type_table . "." . $type_pkey_col,
        # 'chado_table' => $type_table,
        # 'chado_column' => $type_pkey_col,
      ]);
      $properties[] =  new ChadoIntStoragePropertyType($entity_type_id, self::$id, 'link_id', $link_term, [
        'action' => 'store_link',
        'drupal_store' => TRUE,
        'path' => $base_table . '.' . $base_pkey_col . '>' . $type_table . '.' . $type_fkey_col,
        # 'left_table' => $base_table,
        # 'left_table_id' => $base_pkey_col,
        # 'right_table' => $type_table,
        # 'right_table_id' => $type_fkey_col,
      ]);
      $properties[] =  new ChadoTextStoragePropertyType($entity_type_id, self::$id, 'value', $value_term, [
        'action' => 'store',
        'path' => $type_table . '.value',
        # 'chado_table' => $type_table,
        # 'chado_column' => 'value',
      ]);
    }

    // We need to store the numeric cvterm ID for this field.
    $properties[] = new ChadoIntStoragePropertyType($entity_type_id, self::$id, 'type_id', $type_id_term, [
      'action' => 'store',
      'drupal_store' => TRUE,
      'path' => $base_table . '.' . $base_pkey_col . '>' . $type_table . '.' . $type_fkey_col . ';' . $type_column,,
      # 'chado_table' => $type_table,
      # 'chado_column' => $type_column,
      'empty_value' => 0
    ]);
    // This field needs the term name, idspace and accession for proper
    // display of the type.
    $properties[] = new ChadoVarCharStoragePropertyType($entity_type_id, self::$id, 'term_name', $name_term, 128, [
      'action' => 'read_value',
      'path' => $type_table . '.' . $type_column . '>cvterm.cvterm_id;name',
      # 'chado_column' => 'name',
      'as' => 'term_name'
    ]);
    $properties[] = new ChadoVarCharStoragePropertyType($entity_type_id, self::$id, 'id_space', $idspace_term, 128, [
      'action' => 'read_value',
      'path' => $type_table . '.' . $type_column . '>cvterm.cvterm_id;cvterm.dbxref_id>dbxref.dbxref_id;dbxref.db_id>db.db_id;name',
      #'chado_column' => 'name',
      'as' => 'idSpace'
    ]);
    $properties[] = new ChadoVarCharStoragePropertyType($entity_type_id, self::$id, 'accession', $accession_term, 128, [
      'action' => 'read_value',
      'path' => $type_table. '.' . $type_column . '>cvterm.cvterm_id;cvterm.dbxref_id>dbxref.dbxref_id;accession',
      # 'chado_column' => 'accession',
      'as' => 'accession'
    ]);
```
Notice that the `type_id` property fully specifies where the value comes from... as well as all of the fields There is no ambiguity as to where it's value comes from.  Since the `type_id` and `link_id` paths are the same (other than the last column name), then it's clear that the vlaues from those two properties comes from the same join.
