### ISSUE TITLE
Checking for new fields

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1793]
## Issue Description
In Tripal v3 we had the option to add new fields to a content type.  A site admin would go to the content type page, manage the fields and click the button to "Check for new fields".  Then Tripal would run through all of the tables of Chado and add any missing fields to the corresponding content types.   This was useful in Tripal v3 because of these criteria:

1. If a user added a custom table they needed fields for the content type that was mapped to the custom table. In Tripal v3, content types were directly mapped to base tables.
2. Properties in Tripal are unique fields--1 per property type.  So, these can't be added during installation because there's no knowledge about how many properties there may be.  

In Tripal v4 adding new fields dynamically is a bit problematic because 
1.  Content types are not typed to Chado tables, instead fields are.
2.  The content types and fields are now created via YAML files. Theres is no function that looks through Chado to find new tables and new properties and then knows what content type to add them to.  
3.  In Tripal 3 we published content types and added fields, the fields then pulled the appropriate data form Chado. In Tripal v4 we publish fields.  So, some solution for adding new properties has to include publishing of the field records.

## Proposed Solution for Adding Property Fields
Add to the `tripal.tripalentitytype_collection.*` configuration files an entry (per content type) simlar to the following:

```yaml
    -   name: organism_properties
        abstract: true
        content_type: organism
        label: Properties
        type: chado_property_type_default
        description: "An organism property"
        cardinality: -1
        required: false
        storage_settings:
            storage_plugin_id: chado_storage
            storage_plugin_settings:
                base_table: organism
                prop_table: organismprop
        settings:
            termIdSpace: "schema"
            termAccession: "property"
        display:
            view:
                default:
                    region: content
                    label: above
                    weight: 10
            form:
                default:
                    region: content
                    weight: 10
```
In the definition note the new `abstract` element.  If it is true that means this is not a property to be added to the content type when those content types are imported (this field will be ignored), but, it represents the default settings for any field of type `chado_property_type_default`. It also signals that this type of field is appropriate for the given content type.  Then when it comes time to publish the content type, the TripalPublish service will know that any fields with an `abstract` of `true` could have new fields to add to the given type.

Second, we add to the `TripalFieldItemBase` class a static function named `getNewInstances()` function that is empty.  Fields that need to create new instances of fields can do so if they implement this function.   The function should return an array structure identical to the YAML of the `tripal.tripalentitytype_collection.*` configuration, and include the new fields that should be added.  

Prior to publishing, the TripalPublish service will call the `getNewInstances()` function for all entries in the YAML that have an `abstract` set to `true` and then automatically add the new fields.  The TripalPublish service can then (without changes to the publishing part) publish the entries for the new fields.

This will allow us to get rid of the "Check for new fields" button on the fields page of the content type. If a user adds new properties about an organism, for example, then they can re-publish the organism content type and the new properties and values will appear.   

### Branch Name

tv4g1-issue1793-checking_for_new_fields
