### ISSUE TITLE
Adding generic Tripal properties to a content type gives WSOD and error.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1807]
### Tripal Version

4/x

### Drupal Version

10/2

### PostgreSQL Version

N/A

### PHP Version

N/A

### General Description

If you are building a new content type via the Drupal GUI and you want to add some generic Tripal fields to it (e.g. a `tripal_string_type` field) then you will get this error immediatly on trying to add it: 

```
There was a problem creating field Tripal Boolean on Project: Cannot create a StorageProperty object for entity type "tirpal_entity", field type "tirpal_boolean_type", key "value" without a properly formatted term: ":".
```
To explain the cause, first take a look at this code:

https://github.com/tripal/tripal/blob/d09d8c03a36591bd7e47fc3043df364d688ae4df/tripal/src/Plugin/Field/FieldType/TripalStringTypeItem.php#L98-L108

Every single valued field has a `value` property and all properties must have a controlled vocabulary term.  When a field is added vai the YAML files we give the proper `termIdSpace` and `termAccession` so the settings value are set, but when we add the field via the GUI these value are not set.  They are default to empty strings:

https://github.com/tripal/tripal/blob/d09d8c03a36591bd7e47fc3043df364d688ae4df/tripal/src/TripalField/TripalFieldItemBase.php#L25-L28

You might be wondering.... how do we add a Chado Property field without this error?  It also doesn't have a cvterm associated with it until the the user sets the field settings to make it have one.  The reason is that none of the properties that are part of Chado Property field have an empty cvterm.  They are all set programmatically in the `tripalTypes()` function.  But, for these basic Tripal fields, we're relying on the field settings to provide the term (as per the code above), they are not programmatically determined.  Hence we get the error.

So this seems like an easy fix.  First, add the `schema:property` to the terms `tripal.tripal_content_terms.chado_content_terms.yml` YAML file:

```yaml
   -   name: 'schema'
        label: 'Schema.org. Schema.org is sponsored by Google, Microsoft, Yahoo and Yandex. The vocabularies are developed by an open community process.'
        url: 'https://schema.org/'
        idSpaces:
            -   name: 'schema'
                description: "Schema.org"
                urlPrefix: "https://schema.org/{accession}"
        terms:
            -   id: 'schema:name'
                name: 'name'
                description: 'The name of the item.'
            -   id: 'schema:alternateName'
                name: 'alternateName'
                description: 'An alias for the item.'
            -   id: 'schema:comment'
                name: 'comment'
                description: 'Comments, typically from users.'
            -   id: 'schema:description'
                name: 'description'
                description: 'A description of the item.'
            -   id: 'schema:publication'
                name: 'publication'
                description: 'A publication event associated with the item.'
            -   id: 'schema:url'
                name: 'url'
                description: 'URL of the item.'
            -   id: 'schema:additionalType'
                name: 'additionalType'
                description: 'An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in.'
            -   id: 'schema:ItemPage'
                name: 'ItemPage'
                description: 'A page devoted to a single item, such as a particular product or hotel.'
            -   id: 'schema:Property'
                name: 'Property'
                description: 'A property, used to indicate attributes and relationships of some Thing; equivalent to rdf:Property.'

```
Second create an update hook and apply it.

```php
function tripal_chado_update_10402) {

  // Add the missing schema:Property term.
  /** @var \Drupal\tripal\TripalVocabTerms\TripalIdSpaceBase $idSpace **/
  $idsmanager = \Drupal::service('tripal.collection_plugin_manager.idspace');
  $idSpace = $idsmanager->loadCollection('schema', 'chado_id_space');
  $term = $idSpace->getTerm('Property');
  if (!$term) {
    $term = new TripalTerm([
      'name' => 'Property',
      'accession' => 'Property',
      'idSpace' => 'schema',
      'vocabulary' => 'schema',
      'definition' => 'A property, used to indicate attributes and relationships of some Thing; equivalent to rdf:Property.',
    ]);
    $idSpace->saveTerm($term);
  }
}

```
Next, to each `tripalTypes()` function of those basic fields set a default term.

```php
public static function tripalTypes($field_definition) {
    $entity_type_id = $field_definition->getTargetEntityTypeId();
    $storage_settings = $field_definition->getSettings();
    $termIdSpace = $storage_settings['termIdSpace'];
    $termAccession = $storage_settings['termAccession'];

    // If we don't have a term, use a generic property. If the field is
    // added manually via the GUI then the storage settings will then have
    // a term for the field.
    if (!$termIdSpace or !$termAccession) {
      $termIdSpace = 'schema';
      $termAccession = 'Property';
    }

    return [
      new BoolStoragePropertyType($entity_type_id, self::$id, "value", $termIdSpace . ':' . $termAccession),
    ];
  }
```

This fix works!  You can now add a basic Tripal field to any content type.  The field functions as expected too. You can set a value and it saves it.  

I did notice though, that we still have another bug which still needs fixing.    This code doesn't work:

https://github.com/tripal/tripal/blob/d09d8c03a36591bd7e47fc3043df364d688ae4df/tripal/src/Plugin/Field/FieldType/TripalStringTypeItem.php#L98-L103

The reason it doesn't work is becuse the `$field_definition` being passed in is the generic default definition for the field, not the defintion for an instance of the field attached to a content type.  So, even though the GUI allowed us to set a cvterm for the field, we can't get access to it in this function because we don't have those settings.  We only have the default settings for the field.  

The `tripalTypes()` function is static so we can't use `$this->getSetting()` to get the instance settings. The only way I can think to fix this is to pass in the entity type (bundle name) into the `tripalTypes()` function, 

### Steps to reproduce

Try adding a Tripal String field to any content type.
