### ISSUE TITLE
Provide a way to set the base table for a newly defined content type

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1818]
### Task Description

When you define a field through yaml, you can set its base table, e.g.
```
    -   label: Organism
        term: OBI:0100026
        id: organism
        settings:
            chado_base_table: organism
```
When you create a new content type through the GUI, there is no way to save an equivalent setting, so when new fields are added to this new content type, you will have to set the base table for every one. 

We just need a way to select a base table when creating the new content type.

### Branch Name

~~tv4g1-issue1818-select-base-table-for-new-content-type~~
