### ISSUE TITLE
Publication title and pyear fields are set as required but chado says nullable

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#2015]
### Tripal Version

4.x

### Drupal Version

any

### PostgreSQL Version

any

### PHP Version

any

### General Description

The `pyear` field for the publication content type is set in the yaml as a required field.
This matches Tripal 3 behavior, however chado defines this field as nullable.
This is an issue for publish, where we select one required field for finding existing entities.
If a publication is imported without a `pyear` value, or it is entered into the database directly, then if the pub content type is published, duplicate records can result.

I propose we change the field required setting to match the chado setting.
And there will be some publications without a known publication year, so it makes sense.
Sadly this will probably require an update hook to fix existing sites.

Branch: `tv4g1-issue2015-publication-pyear`

In `tripal_chado/config/install/tripal.tripalfield_collection.general_chado.yml`:
```
    -   name: pub_pyear
        content_type: pub
        label: Publication Year
        type: chado_string_type_default
        description:
        cardinality: 1
        # in Tripal 3 this is set as required, although the pub table does not require it.
        required: true
        storage_settings:
            storage_plugin_id: chado_storage
            storage_plugin_settings:
                base_table: pub
                base_column: pyear
            max_length: 255
        settings:
            termIdSpace: TPUB
            termAccession: "0000059"
        display:
          view:
            default:
              region: content
              label: above
              weight: 20
          form:
            default:
              region: content
              weight: 20
```

### Steps to reproduce

```
$bundle_id = 'pub';
$entity_type = 'tripal_entity';

$entityFieldManager = \Drupal::service('entity_field.manager');
$fields = $entityFieldManager->getFieldDefinitions($entity_type, $bundle_id);
foreach ($fields as $field_name => $field_info) {
  $storage_settings = $field_info->getSetting('storage_plugin_settings');
  $base_table = $storage_settings['base_table'] ?? '';
  $base_column = $storage_settings['base_table_dependant']['base_column']
      ?? $storage_settings['base_column'] ?? '';
  $is_required = $field_info->isRequired();
  if ($is_required and $base_table and $base_column) {
    print "Field $field_name on table $base_table column $base_column is required\n";
  }
}
```
Output:
```
Field pub_pyear on table pub column pyear is required
Field pub_title on table pub column title is required
Field pub_uniquename on table pub column uniquename is required
```
