### ISSUE TITLE
Add support for computed fields and explicit exclusion of fields from cache in field collections.

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#2168]
### Task Description

#2162 would introduce fields for the first time that have values dynamically computed by functions and not directly related to a column in the base table. However, the base_column property is mandatory in the schema for field types,
leading to non-existing "dummy" columns having to be specified which isn't ideal. Also, these fields should possibly be excluded from caching their values in Drupal entity tables. 

In #2083 I had tried to add a functionality to annotate a field with the option `drupal_exclude: true` in storage plugin settings, however that didn't make it into the final PR. I therefore propose the following:

- make the base_column attribute optional in the schema
- allow computed fields to be annotated with 'transient' or 'drupal_exclude' to  suppress their caching

It may also be worthwhile to consider allowing the linking of fields to functions or method invocations already on the configuration level. E.g. require that a dynamic field has to be bound to a distinct class implementing: `TripalDynamicFieldInterface` or something like that.

Or possibly have a different plugin from chado_storage handle dynamic fields? 

### Branch Name

tv4g1-issue2168-computedFields

**Comment by laceysanderson** [comment]
Hi @mdondrup, the `drupal_exclude` functionality from your original PR did make it it :-) It is checked [here in TripalStorageBase::isDrupalStoreByFieldNameKey()](https://github.com/tripal/tripal/blob/1011a97e4d600f33504b50bb9a372b6c36932d5b/tripal/src/TripalStorage/TripalStorageBase.php#L318) so you should be able to use that to exclude the property from caching.

For making the base_column optional we'll want to ensure that is carried throughout TripalFieldCollection and Tripal/ChadoStorage. Furthermore, we'll want to pair it with a computed field: it should only be optional if the action is `function`.

> It may also be worthwhile to consider allowing the linking of fields to functions or method invocations already on the configuration level. E.g. require that a dynamic field has to be bound to a distinct class implementing: TripalDynamicFieldInterface or something like that.

I'm not so sure about this... it feels really limiting and would add more to be maintained.

**Comment by mdondrup** [comment]
> the drupal_exclude functionality from your original PR did make it it :-)

Oh dear, I think I was looking into the wrong file (again) 🤦‍♂️  Anyway, I believe the schema still needs to be updated, because I am getting this from automated tests:

```
Exception: Exception when installing config for module tripal_chado, message was: Schema errors for 
tripal.tripalfield_collection.genomic_chado with the following errors: 
tripal.tripalfield_collection.genomic_chado:fields.3.storage_settings.storage_plugin_settings.drupal_exclude missing schema
```

I do not get any error when I update the configuration with drush though.
Here is the field definition:

```
  name: gene_derived_sequence
        content_type: gene
        label: Sequence from alignment
        type: chado_aligned_sequence_type_default
        description: Sequence derived from alignment
        cardinality: 1
        required: false
        storage_settings:
            storage_plugin_id: chado_storage
            storage_plugin_settings:
                base_table: feature
                base_column: dummy_derived_sequence # Need to define a dummy column because it's mandatory.
                drupal_exclude: true # This field is not stored in drupal but is populated by a function.
        settings:
            termIdSpace: SO
            termAccession: "0000001"
        display:
          view:
            default:
              region: content
              label: above
              weight: 40
          form:
            default:
              region: content
              weight: 40
```
